import {atom} from 'recoil';

export const studentDataState = atom({
  key: 'studentData',
  default: [
    {
      id: '60d0fe4f5311236168a109ca',
      class: '6th',
      rollNo: 1,
      firstName: 'Sara',
      lastName: 'Andersen',
      picture: 'https://randomuser.me/api/portraits/women/58.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109cb',
      class: '7th',
      rollNo: 1,
      firstName: 'Edita',
      lastName: 'Vestering',
      picture: 'https://randomuser.me/api/portraits/med/women/89.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109cc',
      class: '6th',
      rollNo: 2,
      firstName: 'Adina',
      lastName: 'Barbosa',
      picture: 'https://randomuser.me/api/portraits/med/women/28.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109cd',
      class: '8th',
      rollNo: 1,
      firstName: 'Roberto',
      lastName: 'Vega',
      picture: 'https://randomuser.me/api/portraits/med/men/25.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109ce',
      class: '8th',
      rollNo: 2,
      firstName: 'Rudi',
      lastName: 'Droste',
      picture: 'https://randomuser.me/api/portraits/med/men/83.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109d0',
      class: '8th',
      rollNo: 3,
      firstName: 'Emre',
      lastName: 'Asikoglu',
      picture: 'https://randomuser.me/api/portraits/med/men/23.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109d1',
      class: '8th',
      rollNo: 4,
      firstName: 'Kent',
      lastName: 'Brewer',
      picture: 'https://randomuser.me/api/portraits/med/men/52.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109d2',
      class: '8th',
      rollNo: 5,
      firstName: 'Evan',
      lastName: 'Carlson',
      picture: 'https://randomuser.me/api/portraits/med/men/80.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109d3',
      class: '8th',
      rollNo: 6,
      firstName: 'Friedrich-Karl',
      lastName: 'Brand',
      picture: 'https://randomuser.me/api/portraits/med/men/7.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109d4',
      class: '8th',
      rollNo: 7,
      firstName: 'Valentin',
      lastName: 'Ortega',
      picture: 'https://randomuser.me/api/portraits/med/men/3.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109d5',
      class: '9th',
      rollNo: 1,
      firstName: 'Sibylle',
      lastName: 'Leibold',
      picture: 'https://randomuser.me/api/portraits/med/women/89.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109d6',
      class: '9th',
      rollNo: 2,
      firstName: 'Elisa',
      lastName: 'Lorenzo',
      picture: 'https://randomuser.me/api/portraits/med/women/89.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109d7',
      class: '8th',
      rollNo: 8,
      firstName: 'Leevi',
      lastName: 'Savela',
      picture: 'https://randomuser.me/api/portraits/med/men/67.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109d8',
      class: '9th',
      rollNo: 3,
      firstName: 'Karoline',
      lastName: 'Sviggum',
      picture: 'https://randomuser.me/api/portraits/med/women/61.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109d9',
      class: '6th',
      rollNo: 3,
      firstName: 'Nuria',
      lastName: 'Leon',
      picture: 'https://randomuser.me/api/portraits/med/women/93.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109da',
      class: '8th',
      rollNo: 9,
      firstName: 'Lance',
      lastName: 'Foster',
      picture: 'https://randomuser.me/api/portraits/med/men/13.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109db',
      class: '7th',
      rollNo: 2,
      firstName: 'Naomi',
      lastName: 'Rodrigues',
      picture: 'https://randomuser.me/api/portraits/med/women/39.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109dc',
      class: '8th',
      rollNo: 10,
      firstName: 'Evan',
      lastName: 'Roux',
      picture: 'https://randomuser.me/api/portraits/med/men/59.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109dd',
      class: '8th',
      rollNo: 11,
      firstName: 'Miguel',
      lastName: 'Lima',
      picture: 'https://randomuser.me/api/portraits/med/men/31.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109de',
      class: '7th',
      rollNo: 3,
      firstName: 'Bessie',
      lastName: 'Burke',
      picture: 'https://randomuser.me/api/portraits/med/women/72.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109df',
      class: '9th',
      rollNo: 4,
      firstName: 'Anaelle',
      lastName: 'Dumas',
      picture: 'https://randomuser.me/api/portraits/med/women/25.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109e0',
      class: '7th',
      rollNo: 4,
      firstName: 'Milly',
      lastName: 'Norman',
      picture: 'https://randomuser.me/api/portraits/med/women/31.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109e1',
      class: '8th',
      rollNo: 12,
      firstName: 'James',
      lastName: 'Black',
      picture: 'https://randomuser.me/api/portraits/med/men/29.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109e2',
      class: '8th',
      rollNo: 13,
      firstName: 'Heinz-Georg',
      lastName: 'Fiedler',
      picture: 'https://randomuser.me/api/portraits/med/men/81.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109e3',
      class: '8th',
      rollNo: 14,
      firstName: 'Vetle',
      lastName: 'Aasland',
      picture: 'https://randomuser.me/api/portraits/med/men/97.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109e4',
      class: '8th',
      rollNo: 15,
      firstName: 'Pwry',
      lastName: 'Shylyrd',
      picture: 'https://randomuser.me/api/portraits/med/men/37.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109e5',
      class: '8th',
      rollNo: 16,
      firstName: 'Adrian',
      lastName: 'Rodriguez',
      picture: 'https://randomuser.me/api/portraits/med/men/45.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109e6',
      class: '7th',
      rollNo: 5,
      firstName: 'Milla',
      lastName: 'Pollari',
      picture: 'https://randomuser.me/api/portraits/med/women/89.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109e7',
      class: '8th',
      rollNo: 17,
      firstName: 'Joey',
      lastName: 'Oliver',
      picture: 'https://randomuser.me/api/portraits/med/men/61.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109e8',
      class: '9th',
      rollNo: 5,
      firstName: 'Cecilie',
      lastName: 'Mortensen',
      picture: 'https://randomuser.me/api/portraits/med/women/56.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109e9',
      class: '8th',
      rollNo: 18,
      firstName: 'Alfredo',
      lastName: 'Omahony',
      picture: 'https://randomuser.me/api/portraits/med/men/76.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109ea',
      class: '9th',
      rollNo: 6,
      firstName: 'Mhrs',
      lastName: 'Hsyny',
      picture: 'https://randomuser.me/api/portraits/med/women/77.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109eb',
      class: '6th',
      rollNo: 4,
      firstName: 'Nella',
      lastName: 'Koivisto',
      picture: 'https://randomuser.me/api/portraits/med/women/77.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109ec',
      class: '8th',
      rollNo: 19,
      firstName: 'Lucas',
      lastName: 'Larsen',
      picture: 'https://randomuser.me/api/portraits/med/men/50.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109ed',
      class: '7th',
      rollNo: 6,
      firstName: 'Kayla',
      lastName: 'Bredesen',
      picture: 'https://randomuser.me/api/portraits/med/women/13.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109ee',
      class: '9th',
      rollNo: 7,
      firstName: 'Beatriz',
      lastName: 'Gutierrez',
      picture: 'https://randomuser.me/api/portraits/med/women/31.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109ef',
      class: '7th',
      rollNo: 7,
      firstName: 'Melanie',
      lastName: 'Pilz',
      picture: 'https://randomuser.me/api/portraits/med/women/32.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109f0',
      class: '8th',
      rollNo: 20,
      firstName: 'Wouter-Jan',
      lastName: 'Wijnker',
      picture: 'https://randomuser.me/api/portraits/med/men/67.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109f2',
      class: '8th',
      rollNo: 21,
      firstName: 'Albert',
      lastName: 'Diez',
      picture: 'https://randomuser.me/api/portraits/med/men/73.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109f3',
      class: '8th',
      rollNo: 22,
      firstName: 'Donald',
      lastName: 'Hopkins',
      picture: 'https://randomuser.me/api/portraits/med/men/73.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109f4',
      class: '8th',
      rollNo: 23,
      firstName: 'Benjamin',
      lastName: 'Holland',
      picture: 'https://randomuser.me/api/portraits/med/men/58.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109f5',
      class: '6th',
      rollNo: 5,
      firstName: 'Charlotte',
      lastName: 'Legrand',
      picture: 'https://randomuser.me/api/portraits/med/women/77.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109f6',
      class: '7th',
      rollNo: 8,
      firstName: 'Madison',
      lastName: 'Ambrose',
      picture: 'https://randomuser.me/api/portraits/med/women/15.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109f7',
      class: '9th',
      rollNo: 8,
      firstName: 'Jolanda',
      lastName: 'Lacroix',
      picture: 'https://randomuser.me/api/portraits/med/women/32.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109f8',
      class: '6th',
      rollNo: 6,
      firstName: 'Signe',
      lastName: 'Madsen',
      picture: 'https://randomuser.me/api/portraits/med/women/84.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109f9',
      class: '8th',
      rollNo: 24,
      firstName: 'Marius',
      lastName: 'Larsen',
      picture: 'https://randomuser.me/api/portraits/med/men/54.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109fa',
      class: '6th',
      rollNo: 7,
      firstName: 'Ann',
      lastName: 'Mason',
      picture: 'https://randomuser.me/api/portraits/med/women/18.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109fb',
      class: '8th',
      rollNo: 25,
      firstName: 'Sohan',
      lastName: 'Pierre',
      picture: 'https://randomuser.me/api/portraits/med/men/77.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109fc',
      class: '8th',
      rollNo: 26,
      firstName: 'Gonzaga',
      lastName: 'Ribeiro',
      picture: 'https://randomuser.me/api/portraits/med/men/10.jpg',
      status: true,
    },
    {
      id: '60d0fe4f5311236168a109cf',
      class: '9th',
      rollNo: 9,
      firstName: 'Carolina',
      lastName: 'Lima',
      picture: 'https://randomuser.me/api/portraits/med/women/5.jpg',
      status: true,
    },
  ],
});

export const chatsDataState = atom({
  key: 'chatsDataState',
  default: [
    // {
    //   id: 0,
    //   userId: '60d0fe4f5311236168a109ca',
    //   timeStamp: 1667828703,
    //   replies: [
    //     {
    //       id: 0,
    //       user_role: 'USER',
    //       created_at: '2022-07-13T01:33:15',
    //       body:
    //         "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
    //     },
    //     {
    //       id: 1,
    //       user_role: 'ADMIN',
    //       created_at: '2022-08-12T01:33:15',
    //       body:
    //         "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
    //     },
    //     {
    //       id: 2,
    //       user_role: 'ADMIN',
    //       created_at: '2022/01/09T01:33:15',
    //       body:
    //         "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
    //     },
    //     {
    //       id: 3,
    //       user_role: 'USER',
    //       created_at: '2022/11/10T01:33:15',
    //       body:
    //         "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
    //     },
    //   ],
    // },
  ],
});
